apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: ClusterIP # set the type of Service
  selector:
    app: backend # referencing the Pod's label
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: theearlofgray/backex