apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer # set the type of Service
  selector:
    app: frontend # referencing the Pod's label
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
---
apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  containers:
  - name: frontend
    image: theearlofgray/frontex
    ports:
    - containerPort: 5000